### ISSUE TITLE
[Tutorial] - Create tutorial to use insertOne()

### ISSUE THREAD

**Issue by ninefyi** [mongodbthailand/mongodbthailand.github.io#5]
Please create a tutorial on how to use insertOne().
Please refer example dataset from this link https://mongoplayground.net/p/dDl_QsJ7z8p

**Comment by jame3032002** [comment]
https://www.mongodb.com/docs/manual/reference/method/db.collection.insertOne/

Should I follow this guideline or write it in my own style?

**Comment by champjss** [comment]
Thanks @jame3032002 for contributing!
